namespace FamilyLINQTraining.DataGeneration.StaticData {
public class Job {
    public static string[] list = {
        "Astronaut",
        "Athlete",
        "Babysitter",
        "Bank Robber",
        "Burglar",
        "Captain",
        "Caretaker",
        "CEO",
        "Cowboy",
        "Chauffeur",
        "Chef",
        "Chemist",
        "Dentist",
        "Doctor",
        "Dog Walker",
        "Engineer",
        "Factory Worker",
        "Farmer",
        "Fire Fighter",
        "Garbage Collector",
        "Gardener",
        "Hitman",
        "Influencer",
        "Janitor",
        "Key Accountmanager",
        "Mascot",
        "Model",
        "Ninja",
        "Nurse",
        "Opera Singer",
        "Pedagogue",
        "Pilot",
        "Pirate",
        "Pizza Chef",
        "Police Officer",
        "Priest",
        "Shepherd",
        "Singer",
        "Soldier",
        "Supervisor",
        "Teacher",
        "Veterenarian",
        "Waittress",
        "Zoo Keeper",
        "Foresters",
        "Biochemist",
        "Food Scientist",
        "Animal Geneticist",
        "Wildlife Biologist",
        "Horti Culturist",
        "Plant Nursery Attendant",
        "Agriculture Teacher",
        "Plant Biologist",
        "Wildlife Inspector",
        "Soil And Plant Scientist",
        "Beekeeper",
        "Aquatic Ecologist",
        "Conservationist",
        "Veterinarian",
        "Zoologist",
        "Groomer",
        "Animal Controlofficer",
        "Kennel Attendant",
        "Pet Walker",
        "Animal Sitter",
        "Animal Shelter Manager",
        "Veterinary Assistant",
        "Animal Nutritionist",
        "Biologist",
        "Wildlife Rehabilitator",
        "Breeder",
        "Veterinary Pathologist",
        "Veterinary Pphthalmologist",
        "Project Manager",
        "Salesmanager",
        "Actuary",
        "Business Teacher",
        "Business Reporter",
        "Admissions Representative",
        "Office Manager",
        "Office Clerk",
        "Assistant Buyer",
        "Business Development Manager",
        "Salon Manager",
        "Makeup Artist",
        "Nail Technician",
        "Message Therapist",
        "Barber",
        "Beautician",
        "Skin Care Specialist",
        "Fashion Designer",
        "Esthetician",
        "Electrologist",
        "Cosmetology Instructor",
        "Hairdresser",
        "Fashion Show Stylist",
        "Spa Manager",
        "Wedding Stylist",
        "Call Center Agent",
        "Client Services Coordinator",
        "Technical Support Representative",
        "Virtual Assistant",
        "Customer Care Associate",
        "Retail Sales Associate",
        "Cashier",
        "Concierge",
        "Customer Service Manager",
        "Help Desk Assistant",
        "Account Coordinator",
        "Service Advisor",
        "Bank Teller",
        "Front Desk Coordinator",
        "Client Services Manager",
        "Art Director",
        "Graphic Designer",
        "Writer",
        "Editor",
        "Illustrator",
        "Public Relations Specialist",
        "Actor",
        "Producer",
        "Web Developer",
        "Architect",
        "Multimedia Animator",
        "Painter",
        "Tattoo Artist",
        "Dancer",
        "Floral Designer",
        "English Teacher",
        "College Professor",
        "Tutor",
        "Test Scorer",
        "Test Administrator",
        "Assistant Professor",
        "Principal",
        "Superintendent",
        "Vice Principal",
        "Substitute Teacher",
        "Librarian",
        "Math Teacher",
        "Science Teacher",
        "Instructional Designer",
        "Guidance Counselor",
        "Civil Engineer",
        "Mechanical Engineer",
        "Chemical Engineer",
        "Biological Engineer",
        "Nuclear Engineer",
        "Aerospace Engineer",
        "Electrical Engineer",
        "Environmental Engineer",
        "Geological Engineer",
        "Marine Engineer",
        "Petroleum Engineer",
        "Safety Engineer",
        "Product Engineer",
        "Compliance Engineer",
        "Senior Process Engineer?",
        "Financial Planner",
        "Financial Advisor",
        "Budget Analyst",
        "Credit Analyst",
        "Financial Services Representative",
        "Financial Manager",
        "Cost Estimator",
        "Loan Officer",
        "Investment Banking Analyst",
        "Financial Auditor",
        "Caregiver",
        "Physical Therapist",
        "Personal Trainer",
        "Pharmacist",
        "Pharmacy Assistant",
        "Dental Hygienist",
        "Orthodontist",
        "Travel Nurse",
        "Dental Assistant",
        "Occupational Therapy Aide",
        "Surgical Technologist",
        "Dietitian",
        "Travel Agent",
        "Housekeeper",
        "Porter",
        "Casino Host",
        "Hotel Clerk",
        "Meeting Planner",
        "Executive Chef",
        "Tour Guide",
        "Flight Attendant",
        "Event Manager",
        "Human Resources Manager",
        "Compensations And Benefits Manager",
        "Administrative Assistant",
        "Human Resources Generalist",
        "Talent Acquisition Coordinator",
        "Executive Recruiter",
        "Human Resources Specialist",
        "Human Resources Director",
        "Human Resources Assistant",
        "Labor Relations Specialist",
        "UXXDesigner",
        "UIDeveloper",
        "ITManager",
        "Computer Programmer",
        "SQLDeveloper",
        "Software Developer",
        "Web Administrator",
        "Data Architect",
        "Business Intelligence Developer",
        "Mobile Application Developer",
        "Information Security Analyst",
        "Front End Web Developer",
        "Java Developer",
        "Database Manager",
        "Software Engineer",
    };
}
}