namespace FamilyLINQTraining.DataGeneration.StaticData {
public class Street {
    public static string[] list = {
        "Abby Park Street",
        "Airport Street",
        "Auburn Avenue",
        "Beatles Avenue",
        "California Street",
        "China Avenue",
        "Copper Street",
        "Dean Avenue",
        "Democracy Avenue",
        "East Hills Avenue",
        "Elisabeth Street",
        "Forest Street",
        "French Street",
        "Glider Avenue",
        "Gold Street",
        "Highway Avenue",
        "Hospital Street",
        "Hurricane Avenue",
        "Impressionist Avenue",
        "King Arthur Istreet",
        "Kings Street",
        "Mandarin Park Lane",
        "Medieval Street",
        "Mitch Cromwood Avenue",
        "Monorail Street",
        "New Orleans Street",
        "Northern Abby Avenueand",
        "Ocean Avenue",
        "Old Port Avenue",
        "Paul Hladovka Avenue",
        "Peoples Avenue",
        "Poets Street",
        "Prachstreetand",
        "Prague Avenue",
        "Rail Avenue",
        "River Street",
        "Sebastian Street",
        "Shall Street",
        "Shopping Avenue",
        "Sobrance Path",
        "Southern Street",
        "State Avenue",
        "Storm Alley",
        "Swit Street",
        "Wallstreet",
        "Western Cesta",
        "Woodstock Street",
    };
}
}